### ISSUE TITLE
Unearthed Conflict with Shrines Structures (2.0.0 Beta 8)

### ISSUE THREAD

**Issue by PhweeDev** [Silverminer007/Shrines#28]
For me, even after clearing the configs, Shrines' mixins seem to conflict with Unearthed's mixins. 
[crash-2021-12-23_18.53.20-fml.txt](https://github.com/Silverminer007/Shrines/files/7771980/crash-2021-12-23_18.53.20-fml.txt)
[latest.log](https://github.com/Silverminer007/Shrines/files/7771981/latest.log)

**Comment by Silverminer007** [comment]
Looks like this was caused by an build issue/project miss configuration on my side. I didn't try to reproduce your issue, because it seems like the Mixins in my mod were broken and the problem wasn't caused by incompatibility. Could you try again with beta 9 and give me a feedback whether it works now?

**Comment by PhweeDev** [comment]
Indeed it works now. Thanks for fixing!
