### ISSUE TITLE
Shrines crashing on server mixin apply 2.0.0 Beta 8

### ISSUE THREAD

**Issue by NighthowlerStudios** [Silverminer007/Shrines#29]
**Describe the bug**
The game crashes when applying the mixin shown in the log, just after the game is done patching items.

**To Reproduce**
1.Install KBP
2. Install latest Shrines Beta 8
3. Try to launch

**Version (please complete the following information):**
 - OS: Windows 10
 - Forge Version 1.16.5-36.2.22
 - Mod Version 2.0.0-Beta 8

**Additional context**
does not crash on Beta 7.  Seems to be a failure applying language packs on the server side for some reason.  Did you accidentally change mixin behaviour when adding those language packs?

https://pastebin.com/LtgK7XBA

**Comment by Silverminer007** [comment]
Was able to approve the issue. After a bit of just trying different things I found out that that was caused by an miss configuration of the project. I now rebuild Beta 8 and published it as Beta 9. Could you try that file again?
While the game crashes when I follow the steps you gave with Beta 8, it doesn't do that with Beta 9

**Comment by NighthowlerStudios** [comment]
Beta 9 is working as intended.  closing issue since it was solved.
