### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by XxttCrystal** [Silverminer007/Shrines#37]
I crashed when I was creating a new world,but I can get into the another world which use old version (but I forget which old version I used)

https://gist.github.com/XxttCrystal/f691eea75d7d59a6d6de5d765e0de2ed
this is the crash report

 - Forge Version [e.g. 1.16.5-36.2.23]
 - Mod Version [e.g. 1.16.5-2.0.1]

**Comment by Silverminer007** [comment]
Thank you for the report. I'm not sure what's the reason for that issue, but you detailed description will help me to find out. I'm going o to fix this as soon as possible

**Comment by XxttCrystal** [comment]
Not at all, I like your mod,It give me a good sense to play minecraft better!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月10日(星期四) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Silverminer007/Shrines] Crash (Issue #37)





 
Thank you for the report. I'm not sure what's the reason for that issue, but you detailed description will help me to find out. I'm going o to fix this as soon as possible
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Silverminer007** [comment]
I've tried to reproduce that crash, but I it didn't crash when I create a new world with version 2.0.1 after I used 1.8.1. Either you've used an other version (do you remember the major version - was it 1.x.x or 2.x.x?) or your circumstances were different. Does it crash all the times you try to create a new world or only some times? Did you modify the structure configuration is any way? Do you use custom structures? If you use custom structures, could you send me the exported packages?

**Comment by username11037** [comment]
I am having the same issue with the 1.18 versions. I tried both the beta and alpha options. With the beta one it crashed every time so I couldn't get passed to launcher but the alpha one got me to making a world but then it crashes.

> I've tried to reproduce that crash, but I it didn't crash when I create a new world with version 2.0.1 after I used 1.8.1. Either you've used an other version (do you remember the major version - was it 1.x.x or 2.x.x?) or your circumstances were different. Does it crash all the times you try to create a new world or only some times? Did you modify the structure configuration is any way? Do you use custom structures? If you use custom structures, could you send me the exported packages?

**Comment by Silverminer007** [comment]
This might be caused by this in 1.18.1 and 1.18.2: https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone

The issue with the beta versions might also be that you missed installing dynamicregistries too: https://silverminer007.github.io/ShrinesWiki/wiki/en_us/users/dependencies.html

Could you please response if that fixed your issues?

**Comment by username11037** [comment]
neither worked. It crashed at the launcher.

**Comment by Silverminer007** [comment]
Sorry for my late response. Is there a log created or does it say something when it crashes? Is there any other mod involved? It's for 1.18.1 & 1.18.2, isn't it? I guess the two issues aren't related, because one crashes on start up the other on world load. Could create a new issue for the 1.18.1 & 1.18.2 version?

**Comment by Silverminer007** [comment]
> I crashed when I was creating a new world,but I can get into the another world which use old version (but I forget which old version I used)
> 
> https://gist.github.com/XxttCrystal/f691eea75d7d59a6d6de5d765e0de2ed this is the crash report
> 
>     * Forge Version [e.g. 1.16.5-36.2.23]
> 
>     * Mod Version [e.g. 1.16.5-2.0.1]

It seems like any structure uses a spacing with value 0. I don't know if the issue is still up to date, but you could try binary search (keep shrines all the time, remove half of the mods, check if the issue still occurs, if yes, repeat with removing half of the mods, if not try with the other half) and report the mod to me. If you configured shrines structures, please check if you set separation or distance to 0 anywhere.
