### ISSUE TITLE
Crash on minecraft client and server mod loading

### ISSUE THREAD

**Issue by kaybi-gh** [Silverminer007/Shrines#39]
**Describe the bug**
Minecraft crashes on shrines mod loading (both client and server).

**To Reproduce**
- Install modpack https://www.curseforge.com/minecraft/modpacks/mineshafts-monsters
- Update shrines from 1.8.1 to 2.2.0
- Launch the game once, it will work fine
- Close the game then launch it again, it will crash

**Expected behavior**
No crash like on the first launch.

**Version:**
 - OS: Windows 10
 - Forge Version: 1.16.5-36.2.0
 - Mod Version: 1.16.5-2.2.0

**Additional context**
I noticed that there was some uppercases directories created in the shrines-saves directory (Packets, Included Structures, etc) and it seems to be the problem with path characters convention?
Latest.log on pastebin here: https://pastebin.com/K6VyMsxP

**Comment by Silverminer007** [comment]
Could you send the crash-report too? I can't find the crash message in the latest.log

**Comment by Silverminer007** [comment]
I found the issue. This is probably caused by an issue with Windows systems. The paths on windows systems are separated with '\' and on Unix systems with '/'. I've missed to convert the '\' to '/', which causes issues, because Minecraft & Shrines are working with '/' internally.I haven't noticed that yet, because I'm running on a Linux system. Patch 2.2.1 should fix this issue. If there is still a issue with shrines, please send the new log, otherwise close this issue.

Another hint from my side: Because of the vulnerability in Log4j, you should update forge to at least 36.2.20

**Comment by kaybi-gh** [comment]
I gave it a try and it 100% fixed the issue thank you for being that amazingly fast!
